// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_level_6 = "CgkIk42autMMEAIQDA"; // <GPGSID>
        public const string leaderboard_level_3 = "CgkIk42autMMEAIQCQ"; // <GPGSID>
        public const string achievement_thanks_but_no_thanks = "CgkIk42autMMEAIQAw"; // <GPGSID>
        public const string leaderboard_level_1 = "CgkIk42autMMEAIQBw"; // <GPGSID>
        public const string achievement_vengeance = "CgkIk42autMMEAIQFg"; // <GPGSID>
        public const string achievement_build_that_bonus = "CgkIk42autMMEAIQFA"; // <GPGSID>
        public const string leaderboard_level_5 = "CgkIk42autMMEAIQCw"; // <GPGSID>
        public const string leaderboard_level_4 = "CgkIk42autMMEAIQCg"; // <GPGSID>
        public const string leaderboard_level_7 = "CgkIk42autMMEAIQDQ"; // <GPGSID>
        public const string leaderboard_level_9 = "CgkIk42autMMEAIQDw"; // <GPGSID>
        public const string leaderboard_level_8 = "CgkIk42autMMEAIQDg"; // <GPGSID>
        public const string achievement_lets_get_serious = "CgkIk42autMMEAIQAg"; // <GPGSID>
        public const string achievement_costar = "CgkIk42autMMEAIQAQ"; // <GPGSID>
        public const string achievement_eat_my_dust = "CgkIk42autMMEAIQBg"; // <GPGSID>
        public const string achievement_boldly_running_away = "CgkIk42autMMEAIQBQ"; // <GPGSID>
        public const string achievement_barely_made_it = "CgkIk42autMMEAIQEw"; // <GPGSID>
        public const string achievement_quite_the_collector = "CgkIk42autMMEAIQBA"; // <GPGSID>
        public const string achievement_beegone = "CgkIk42autMMEAIQEg"; // <GPGSID>
        public const string leaderboard_level_2 = "CgkIk42autMMEAIQCA"; // <GPGSID>
        public const string leaderboard_all_levels_total = "CgkIk42autMMEAIQEQ"; // <GPGSID>
        public const string achievement_bigger_bonus_better = "CgkIk42autMMEAIQFQ"; // <GPGSID>
        public const string leaderboard_final_level = "CgkIk42autMMEAIQEA"; // <GPGSID>
        public const string achievement_respect = "CgkIk42autMMEAIQFw"; // <GPGSID>

}

